package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

/**
 * Panel de consola para el servidor.
 * 
 * Esta clase representa un panel gráfico que forma parte de la interfaz del servidor.
 * Su propósito puede incluir mostrar información de log, mensajes o controles de la consola del servidor.
 * 
 * Extiende {@code javax.swing.JPanel} y se inicializa con los componentes definidos en el método {@code initComponents()}.
 * 
 * @author Andres Felipe
 */

public class PanelConsolaServidor extends javax.swing.JPanel {

    /**
     * Constructor del panel de consola del servidor.
     * Inicializa los componentes gráficos definidos en el formulario.
     */
    public PanelConsolaServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsola = new javax.swing.JTextArea();
        jButtonEmpezarJuego = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTextAreaConsola.setEditable(false);
        jTextAreaConsola.setColumns(20);
        jTextAreaConsola.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsola);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonEmpezarJuego.setText("Empezar Juego");
        add(jButtonEmpezarJuego, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEmpezarJuego;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaConsola;
    // End of variables declaration//GEN-END:variables
}
