package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

import java.awt.Font;
import javax.swing.JToggleButton;

/**
 *
 * @author Andres Felipe
 */
public class PanelJuego extends javax.swing.JPanel {

    public JToggleButton[] cartas = new JToggleButton[40];
    
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
    }
    
    public void anadirBoton(int numeroBoton){
        JToggleButton carta = new JToggleButton("?");
        carta.setFont(new Font("Arial", Font.PLAIN, 30 ));
        cartas[numeroBoton]=carta;
        jPanelBotones.add(carta);
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNumeroIntentos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumeroParejas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Numero de Intentos:");
        jPanel4.add(jLabel3);

        jLabelNumeroIntentos.setText("jLabel4");
        jPanel4.add(jLabelNumeroIntentos);

        jPanel1.add(jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Numero de Parejas:");
        jPanel3.add(jLabel1);

        jLabelNumeroParejas.setText("jLabel2");
        jPanel3.add(jLabelNumeroParejas);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Concentrese");
        add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanelBotones.setLayout(new java.awt.GridLayout(5, 8));
        add(jPanelBotones, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelNumeroIntentos;
    public javax.swing.JLabel jLabelNumeroParejas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanelBotones;
    // End of variables declaration//GEN-END:variables
}
