package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

/**
 *
 * @author Andres Felipe
 */
public class PanelJuego extends javax.swing.JPanel {

    public JToggleButton[] cartas;
    
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        this.cartas = new JToggleButton[40];
    }
    
    public void anadirBoton(int numeroBoton){
        JToggleButton carta = new JToggleButton();
        ImageIcon iconNormal = new ImageIcon(System.getProperty("user.dir") + "/src/edu/progAvUD/parcialSegundoCorteAvanzada/servidor/imagenes/dorso.png");
        carta.setIcon(iconNormal);
        cartas[numeroBoton]=carta;
        jPanelBotones.add(carta);
        revalidate();
    }
    
    public void ponerImagenCarta(int idCarta, int idImagen){
        JToggleButton carta = cartas[idCarta];
        ImageIcon iconSeleccionado = new ImageIcon(System.getProperty("user.dir") + "/src/edu/progAvUD/parcialSegundoCorteAvanzada/servidor/imagenes/"+idImagen+".jpg");
        carta.setSelectedIcon(iconSeleccionado);
        revalidate();
    }
    
    public void seleccionarCarta(int idCarta){
        JToggleButton carta = cartas[idCarta];
        carta.setSelected(true);
        revalidate();
    }
    
    public void deseleccionarCarta(int idCarta){
        JToggleButton carta = cartas[idCarta];
        carta.setSelected(false);
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelJugador = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNumeroIntentos = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelNumeroParejas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Jugador:");
        jPanel6.add(jLabel1);

        jLabelJugador.setText("jLabel2");
        jPanel6.add(jLabelJugador);

        jPanel1.add(jPanel6);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Numero de Intentos:");
        jPanel8.add(jLabel6);

        jLabelNumeroIntentos.setText("jLabel8");
        jPanel8.add(jLabelNumeroIntentos);

        jPanel1.add(jPanel8);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Numero de Parejas:");
        jPanel7.add(jLabel9);

        jLabelNumeroParejas.setText("jLabel10");
        jPanel7.add(jLabelNumeroParejas);

        jPanel1.add(jPanel7);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Concentrese");
        add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanelBotones.setLayout(new java.awt.GridLayout(5, 8));
        add(jPanelBotones, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelJugador;
    public javax.swing.JLabel jLabelNumeroIntentos;
    public javax.swing.JLabel jLabelNumeroParejas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanelBotones;
    // End of variables declaration//GEN-END:variables
}
