package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

/**
 *
 * @author Andres Felipe
 */
public class PanelInicial extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicial
     */
    public PanelInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonPropiedadesBD = new javax.swing.JButton();
        jButtonPropiedadesJugadores = new javax.swing.JButton();
        jButtonPropiedadesSockets = new javax.swing.JButton();

        jLabel1.setText("Antes de empezar, selecciona el archivo de propiedades del Socket");

        jButtonPropiedadesBD.setText("Seleccionar Propiedades BD");

        jButtonPropiedadesJugadores.setText("Seleccionar Propiedades Jugadores");

        jButtonPropiedadesSockets.setText("Seleccionar Propiedades Sockets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPropiedadesBD)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonPropiedadesSockets))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButtonPropiedadesJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonPropiedadesBD)
                .addGap(12, 12, 12)
                .addComponent(jButtonPropiedadesSockets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPropiedadesJugadores)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonPropiedadesBD;
    public javax.swing.JButton jButtonPropiedadesJugadores;
    public javax.swing.JButton jButtonPropiedadesSockets;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
