package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setVisible(true);
    }

    /**
     * Muestra un mensaje de éxito en una ventana emergente.
     *
     * @param mensaje el texto que se mostrará.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un mensaje de error en una ventana emergente.
     *
     * @param mensaje el texto que se mostrará.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Abre un diálogo para que el usuario seleccione un archivo `.properties`.
     *
     * @return el archivo seleccionado o null si se cancela.
     */
    public File pedirArchivoPropiedades() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/main/java/edu/progAvUD/parcialSegundoCorteAvanzada/servidor/data");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .properties", "properties"));
        fileChooser.showOpenDialog(null);
        return fileChooser.getSelectedFile();
    }

    /**
     * Muestra un JOptionPane con un campo de texto para que el usuario escriba
     * un dato faltante.
     *
     * @param datoFaltante nombre del dato que falta.
     * @return el texto ingresado por el usuario.
     */
    public String mostrarJOptionEscribirDatoFaltante(String datoFaltante) {
        String mensaje = "Hace falta el dato de '" + datoFaltante + "'.\nEscriba el dato:";

        JTextField textField = new JTextField();
        Object[] contenido = {mensaje, textField};
        Object[] botones = {"Aceptar"};

        JOptionPane optionPane = new JOptionPane(
                contenido,
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.DEFAULT_OPTION,
                null,
                botones,
                botones[0]
        );

        JDialog dialog = optionPane.createDialog("Dato Faltante");
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setModal(true);
        dialog.setVisible(true);

        return textField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
