package edu.progAvUD.parcialSegundoCorteAvanzada.servidor.vista;

import edu.progAvUD.parcialSegundoCorteAvanzada.servidor.control.ControlGrafico;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public PanelInicial panelInicial;
    public PanelJuego panelJuego;
    public PanelConsolaServidor panelConsolaServidor;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        initComponents();
        this.panelInicial = new PanelInicial();
        this.panelJuego = new PanelJuego();
        this.panelConsolaServidor = new PanelConsolaServidor();
        setVisible(true);
    }

    /**
     * Muestra un mensaje de éxito en una ventana emergente.
     *
     * @param mensaje el texto que se mostrará.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un mensaje de error en una ventana emergente.
     *
     * @param mensaje el texto que se mostrará.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Abre un diálogo para que el usuario seleccione un archivo `.properties`.
     *
     * @return el archivo seleccionado o null si se cancela.
     */
    public File pedirArchivoPropiedades() {
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir") + "/src/edu/progAvUD/parcialSegundoCorteAvanzada/servidor/data");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos .properties", "properties"));
        fileChooser.showOpenDialog(null);
        return fileChooser.getSelectedFile();
    }

    /**
     * Muestra un JOptionPane con un campo de texto para que el usuario escriba
     * un dato faltante.
     *
     * @param datoFaltante nombre del dato que falta.
     * @return el texto ingresado por el usuario.
     */
    public String mostrarJOptionEscribirDatoFaltante(String datoFaltante) {
        String mensaje = "Hace falta el dato de '" + datoFaltante + "'.\nEscriba el dato:";

        JTextField textField = new JTextField();
        Object[] contenido = {mensaje, textField};
        Object[] botones = {"Aceptar"};

        JOptionPane optionPane = new JOptionPane(
                contenido,
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.DEFAULT_OPTION,
                null,
                botones,
                botones[0]
        );

        JDialog dialog = optionPane.createDialog("Dato Faltante");
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setModal(true);
        dialog.setVisible(true);

        return textField.getText();
    }
    
    /**
     * Cambia el panel visible en la ventana principal.
     * Ajusta el tamaño, centra la ventana en pantalla y actualiza la interfaz gráfica.
     *
     * @param panel Panel que se desea mostrar en la ventana principal.
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate(); // Refresca el layout
        repaint(); // Redibuja la ventana
    }
    
    /**
     * Muestra un mensaje en el área de texto de la consola del servidor.
     * 
     * @param mensaje Texto que se desea añadir al log de la consola.
     */
    public void mostrarMensajeConsolaServidor(String mensaje) {
        panelConsolaServidor.jTextAreaConsola.append(mensaje + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
